services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mm-network
    ports:
      - "127.0.0.1:27017:27017"

  service-api:
    build: .
    restart: always
    container_name: service-api
    ports:
      - "127.0.0.1:7000:7000"
    env_file:
      - .env
    develop:
      watch:
        - path: .
          target: /api
          action: rebuild
    depends_on:
      - mongodb
    networks:
      - mm-network

volumes:
  mongo-data:

networks:
  mm-network:
    driver: bridge
    external: true
