services:
  service-api:
    build: .
    restart: always
    container_name: service-api
    ports:
      - "127.0.0.1:7000:7000"
    env_file:
      - .env
    develop:
      watch:
        - path: .
          target: /api
          action: rebuild
    networks:
      - mm-network

networks:
  mm-network:
    driver: bridge
    external: true
