// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/trading-centers": {
            "get": {
                "description": "Get all trading centers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trading_centers"
                ],
                "summary": "Get trading centers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/veggies": {
            "get": {
                "description": "Get all veggies with their classes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "veggies"
                ],
                "summary": "Get all veggies with classes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/config": {
            "get": {
                "description": "Get the configuration of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/history-prices": {
            "get": {
                "description": "Get all history prices of all veggies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history_prices"
                ],
                "summary": "Get history prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/history-prices/latest": {
            "get": {
                "description": "Get the latest history prices of all veggies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history_prices"
                ],
                "summary": "Get latest history prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/prices": {
            "get": {
                "description": "Get all history prices of a veggie by its ID and Class",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history_prices"
                ],
                "summary": "Get veggie prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Veggie ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Veggie Class",
                        "name": "class",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/veggies": {
            "get": {
                "description": "Get all veggies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "veggies"
                ],
                "summary": "Get all veggies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/veggies/classes": {
            "get": {
                "description": "Get all veggie classes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "veggies"
                ],
                "summary": "Get all veggie classes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{tradingCenter}/veggies/{id}": {
            "get": {
                "description": "Get veggie by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "veggies"
                ],
                "summary": "Get veggie by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading Center",
                        "name": "tradingCenter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Veggie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.HTTPErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.HTTPErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "utils.HTTPSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
